from __future__ import annotations

import shutil
import time
from pathlib import Path

from git import Repo as GitRepo
from github import Github

from app.config import settings

_client: Github | None = None


def _github() -> Github:
    print("[PatchPilot] Initializing GitHub client...")
    global _client
    if _client is None:
        if not settings.github_token:
            raise ValueError("Set GITHUB_TOKEN in your .env file.")
        _client = Github(settings.github_token)
    return _client


def clone_repo(full_name: str) -> Path:
    print(f"[PatchPilot] Cloning repository {full_name}...")
    clone_dir = settings.repos_path / f"{full_name.replace('/', '_')}_{int(time.time())}"
    clone_url = f"https://x-access-token:{settings.github_token}@github.com/{full_name}.git"
    GitRepo.clone_from(clone_url, str(clone_dir), depth=1)
    return clone_dir


def create_branch(repo_path: Path, branch_name: str) -> None:
    print
    GitRepo(str(repo_path)).git.checkout("-b", branch_name)


def commit_changes(repo_path: Path, message: str) -> None:
    print(f"[PatchPilot] Committing changes with message: {message}")
    repo = GitRepo(str(repo_path))
    repo.git.add("--all")
    repo.config_writer().set_value("user", "name", "PatchPilot Bot").release()
    repo.config_writer().set_value("user", "email", "patchpilot@bot.dev").release()
    repo.index.commit(message)


def push_branch(repo_path: Path, branch_name: str) -> None:
    print(f"[PatchPilot] Pushing branch {branch_name}...")
    GitRepo(str(repo_path)).git.push("origin", branch_name)


def create_pull_request(full_name: str, branch_name: str, title: str, body: str, issue_number: int) -> str:
    print(f"[PatchPilot] Creating pull request for {full_name}...")
    repo = _github().get_repo(full_name)
    full_body = f"{body}\n\n---\n\n🤖 *Generated by PatchPilot — Resolves #{issue_number}*"
    pr = repo.create_pull(title=title, body=full_body, head=branch_name, base=repo.default_branch)
    return pr.html_url


def get_issue(full_name: str, issue_number: int) -> dict:
    print(f"[PatchPilot] Fetching issue {issue_number} from {full_name}...")
    repo = _github().get_repo(full_name)
    issue = repo.get_issue(number=issue_number)
    return {"title": issue.title, "body": issue.body or "", "url": issue.html_url}


def cleanup_repo(repo_path: Path) -> None:
    print(f"[PatchPilot] Cleaning up repository {repo_path}...")
    shutil.rmtree(repo_path, ignore_errors=True)
